spring:
  application:
    name: rate-limiter-service

  spring:
    data:
      redis:
        host: ${SPRING_DATA_REDIS_HOST:localhost}
        port: ${SPRING_DATA_REDIS_PORT:6379}

springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true